name: publish OllieBear.Infrastructure.Transport.RabbitMQ to nuget

on:
  push:
    branches:
      - main # Your default release branch
    paths:
      - 'src/Infrastructure.Transport.RabbitMQ/**'
jobs:
  build:
    name: list OllieBear.Infrastructure.Transport.RabbitMQ on nuget.org
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore OllieBear.Infrastructure.Transport.RabbitMQ project dependencies
      run: dotnet restore src/Infrastructure.Transport.RabbitMQ/Infrastructure.Transport.RabbitMQ.csproj
    - name: Build OllieBear.Infrastructure.Transport.RabbitMQ project
      run: dotnet build src/Infrastructure.Transport.RabbitMQ/Infrastructure.Transport.RabbitMQ.csproj --no-restore --configuration Release
    - name: Pack OllieBear.Infrastructure.Transport.RabbitMQ project
      run: dotnet pack src/Infrastructure.Transport.RabbitMQ/Infrastructure.Transport.RabbitMQ.csproj --no-build --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg -o .
    - name: Publish OllieBear.Infrastructure.Transport.RabbitMQ package to NuGet
      run: dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
